# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Association Internationale des Études Arméniennes
author:
  en: AIEA Secretary
  fr: Secrétaire AIEA
  hy: ՀՈՄԸ քարտուղար
description: 
  en: Website of the Association Internationale des Études Arméniennes. News and information about the AIEA, its executive, its membership and its activities.
  fr: Site de l'Association Internationale des Études Arméniennes. Nouvelles et informations sur l'AIEA, son exécutif, ses membres et ses activités.
  hy: Հայկական Ուսումներու Միջազգային Ընկերակցութեան կայք։ ՀՈՄԸ Նորութիւններ եւ տեղեկատւութիւն, գործադիրի, անդամների և գործունէութեան մասին։
email: info@aiearmeniennes.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aiearmeniennes.org/" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: AIEAArmenian
github_username: AIEArmeniennes

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ["en", "fr", "hy"]
langsep: " | "
default_lang: "en"
exclude_from_localization: ["assets", "public"]
parallel_localization: true
lang_from_path: true
date_format: "%d %B %Y"

posts_heading:
  en: News
  fr: Nouvelles
  hy: Նորութիւններ

collections:
  artsakh:
    output: true
    permalink: /:collection/:title/
# I have commented out the ordering parameter, since VC wanted alphabetic order now… Ordered by path automatically.
#    order:
#      - Dadivank-monastery.md
#      - Gandzasar-monastery.md
#      - Hasan-Jola.md
#      - Mongols.md
#      - Alb-lang.md
#      - Alb-script.md
#      - Udi-lang.md


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - oldsite/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
